=== DVivier/OCR/xml/galerieart.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <!-- XSD se reposant sur le langage XML, il faut une balise racine, ici, <xs:schema> -->

    <xs:element name="oeuvre">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="type" type="xs:string"/>
                <xs:element name="auteur" type="xs:string" minOccurs="0"/>
                <xs:element name="titre" type="xs:string" minOccurs="0"/>
                <xs:element name="prix" type="xs:decimal" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="galerie">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="gerant" type="xs:string"/>
                <xs:element ref="oeuvre" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="adresse" type="xs:string" use="required" />
        </xs:complexType>
    </xs:element>


</xs:schema>

=== DVivier/OCR/xml/galerieart.xml
<?xml version="1.0" encoding="UTF-8"?>

<galerie
        xs:noNamespaceSchemaLocation="galerieart.xsd"
        xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
        adresse="2 rue de la poupee qui tousse"
>
    <gerant>Polux</gerant>
    <oeuvre>
        <type>peinture</type>
        <auteur>Kandinsky</auteur>
        <titre>lignes dintersection</titre>
        <prix>200</prix>
    </oeuvre>
    <oeuvre>
        <type>gravure</type>
        <auteur>graveur1</auteur>
        <prix>5</prix>
    </oeuvre>
    <oeuvre>
        <type>sculpture</type>
        <auteur>rodin</auteur>
        <titre>penseur</titre>
    </oeuvre>
    <oeuvre>
        <type>tapisserie</type>
        <auteur>Delaunay</auteur>
    </oeuvre>
    <oeuvre>
        <type>peinture</type>
        <auteur>peintre2</auteur>
    </oeuvre>
</galerie>
